import Head from "next/head";
import Image from "next/image";
import Auth from "@/components/Auth";
import { useAuthState } from "react-firebase-hooks/auth";
// import firebaseClient from "firebase/client";

export default function Home() {
  // const [user, loading, error] = useAuthState(firebaseClient.auth());
  // console.log({ loading, user });
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Auth />
    </div>
  );
}
