import Head from "next/head";
import Image from "next/image";
import Auth from "@/components/Auth";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Auth />
    </div>
  );
}
